### ISSUE TITLE
TD-ISRM - Cannot bind EU/LBT ACCST receiver with FLEX 1.5.2 firmware On X20 PRO

### ISSUE THREAD

**Issue by spadeadam** [FrSkyRC/RF_Feedback_Group#28]
I have the latest X20 PRO ISRM 1.1.13 installed and the X20 PRO running FLEX 1.5.2 will not bind with an XSR receiver with firmware 2.1.0 EU/LBT (it does bind if the XSR is flashed with FCC). 

My X20 running Flex 1.5.2 does bind with the XSR running ACCST 2.1.0 EU/LBT

the X20 PRO is EU version set at 868M

**Comment by mawzthefinn** [comment]
Fix should be in latest TD ISRM firmware
