### ISSUE TITLE
R9 SX not working prporly

### ISSUE THREAD

**Issue by sigurdma** [FrSkyRC/RF_Feedback_Group#43]
Hello
X20pro latest all.. It happened after latest RF firmware update I suspect.
R9 SX is not working correct. Tried two of them, same result. Se picture.
Falling in and out on rssi continuously. The rssi bar at right top is also going up and down. Somebody tried the same?
(TD R10 is ok)
![ErrorSX9](https://github.com/user-attachments/assets/ddd49db1-c612-4ed7-9322-cf65ea733318)

I can confirm that going back 1.1.13 is ok.

**Comment by SmartTommy** [comment]
Thank you for your test, could you please test the new firmware?
[TD-ISRMPro_20240907_Beta.zip](https://github.com/user-attachments/files/16914177/TD-ISRMPro_20240907_Beta.zip)

**Comment by mgsanna** [comment]
> Thank you for your test, could you please test the new firmware? [TD-ISRMPro_20240907_Beta.zip](https://github.com/user-attachments/files/16914177/TD-ISRMPro_20240907_Beta.zip)

I had the same problems with R9 Slim - OTA, solved with the new firmware of X20PRO 1.1.15
Thanks

**Comment by sigurdma** [comment]
Hello

Now its OK. Tested ok with R9 SX (and also TD R10)

Regards Sigurd

Den 07.09.2024 09:38, skrev Marco Gualtiero Sanna:

**Comment by Dsrenger** [comment]
Is this issue incorperated into the current firmware 1.1.14 I can find on www.frsky-rc.com?

**Comment by SmartTommy** [comment]
> Is this issue incorperated into the current firmware 1.1.14 I can find on [www.frsky-rc.com](http://www.frsky-rc.com)?

The TD_ISRMPro_3.0.0 firmware fixed it.   you can find here:https://github.com/FrSkyRC/RF_Feedback_Group/releases/tag/Beta
