### ISSUE TITLE
RB35s Ch9 current is not detectable on latest FW

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/RF_Feedback_Group#46]
latest firmware RB35S we only get CH1-8 when discovering new sensors.
We should get CH1-9

Thanks

**Comment by SmartTommy** [comment]
we test the last firmware:https://www.frsky-rc.com/rb-35-rb-35s/ , it works normal, current CH9 display as it should.

**Comment by noamkrief** [comment]
@SmartTommy Interesting. You are getting CH9.

I'm also on the very latest FW  for RB35S and it stops at CH8 current. 
Discover new sensors does not bring back CH9.

This started when I installed the new RB35S FW for the 3.0 lua and set the data rate to maximum.
Then I recovered the RB35S by going to an old FW and then back to the new FW.

How should I proceed with troubleshooting?
Thanks

**Comment by SmartTommy** [comment]
does the "Output1 voltage" and "Output2 voltage" display normal?

**Comment by noamkrief** [comment]
@SmartTommy 
Yes. Both are there, and reading. Both fluctuating between 7.0 and 7.1v
Both are alive and well!

**Comment by noamkrief** [comment]
@SmartTommy 
I tried to delete CH8 to see if it comes back.
Of course it does NOT, because they are all connected. You know this right??? :)
So I deleted CH1-8 and re-discovered.
Only CH1-8 came back :( no channel 9.

**Comment by noamkrief** [comment]
@SmartTommy 
GOT IT!!!!!
Somehow CH9 is part of either Output1V or Output 2V

I deleted both output1/2V and re-discovered.
Output 1 & 2 came back along with Ch9.

Please remember this when someone else has this issue :)
Cheers!!!!
