### ISSUE TITLE
AUto-level offset problem with ail1 one on pin 7

### ISSUE THREAD

**Issue by Kat-Man-DEW** [FrSkyRC/RF_Feedback_Group#53]
I have a X20 Pro AW and TD SR10. I updated the TD SR10 firmware and calibrated it before installing it.

I had to move right ailerons to another channel in the receiver options so I could get SPort on pin 1. I moved it to pin 7. The ailerons and stabilization work properly, but when I adjust **_Aileron Auto lvl Offset_** it only effects the left aileron (ail 2).

Both aileron channels (1 and 5) are set to aileron function in the setup Lua. The only way I can adjust the ail2 auto-level offset is by adjusting ail3 on the second page of the STAB settings.

**Comment by SmartTommy** [comment]
could you try move SPORT to Pin7, and recover the PIN1 to aileron channel?
