### ISSUE TITLE
TW R8 fails update over OTA

### ISSUE THREAD

**Issue by kehheli** [FrSkyRC/RF_Feedback_Group#57]
just bought the x20 rs and a tw r8 receiver. i have completed all updates to the tx but cannot update the rx using internal OTA. it fails with unsupported rx.
is there going to be a fix for this very soon as i have several models to setup with the frsky system, replacing spectrum dsm2 stuff.

**Comment by SmartTommy** [comment]
you can get the 3.0.0 beta firmware here :https://github.com/FrSkyRC/RF_Feedback_Group
