### ISSUE TITLE
What is the correct firmware for internal module X20 RS

### ISSUE THREAD

**Issue by Eduardoesteban1694** [FrSkyRC/RF_Feedback_Group#63]
Hi, I would like to know which is the correct version of the internal module of an X20 RS radio, since there are no download files for this radio version on the FrSky page.

Thanks.

**Comment by bsongis-frsky** [comment]
I transfer it to the RF team, I am not sure of the answer

**Comment by SmartTommy** [comment]
X20RS use the TD-ISRMPro firmware
