### ISSUE TITLE
TW X14 Ethos 1.6.0 RC2 and ISRM 3.0.0 - RxBatt missing

### ISSUE THREAD

**Issue by gernotw** [FrSkyRC/RF_Feedback_Group#68]
with TW X14 Ethos 1.6.0 RC2 and ISRM 3.0.0 the receiver voltage seems to miss in combination with a X4R with uni firmware V2-EU rev.83.

![screenshot-2024-12-02-51076](https://github.com/user-attachments/assets/2d294de4-2ac9-4cd1-83cf-ed477036f12f)

**Comment by SmartTommy** [comment]
please use the 3.0.1 RC1 firmware:

[TW-ISRM_3.0.1_RC1.zip](https://github.com/user-attachments/files/18143004/TW-ISRM_3.0.1_RC1.zip)
https://github.com/FrSkyRC/RF_Feedback_Group/releases/tag/v3.0.1rc1

**Comment by gernotw** [comment]
with X14 1.6.0-RC8, TW-IRSM 3.0.1 RC1 and X4R with uni firmware V2-EU rev.83. the RxBatt is found but the value is frozen (after rebinding the receiver, delete all sensors, find all sensors)

**Comment by gernotw** [comment]
From MikeHRC I got just the hint, that 4V is the lower limit of power supply for X4R! Using 5V telemetry / RxBatt is ok!! The issue can be closed!
