### ISSUE TITLE
RB 25S no access to ADV sensors via S.Port and FBUS

### ISSUE THREAD

**Issue by 3wintro** [FrSkyRC/RF_Feedback_Group#75]
RB 25S via S.Port and FBUS no access to ADV sensors since update to FW 3.0.1 TD-ISRM on XES. No matter which TD series receiver. Setting the ID is no longer possible. It only works when plugged directly into the receiver.

**Comment by SmartTommy** [comment]
> RB 25S via S.Port and FBUS no access to ADV sensors since update to FW 3.0.1 TD-ISRM on XES. No matter which TD series receiver. Setting the ID is no longer possible. It only works when plugged directly into the receiver.


did it works before you update the FW 3.0.1?

**Comment by 3wintro** [comment]
I just tried it again, all flashed to the old status. Does not work either.

**Comment by SmartTommy** [comment]
> I just tried it again, all flashed to the old status. Does not work either.

https://github.com/FrSkyRC/RF_Feedback_Group/issues/66#event-15544226257
