### ISSUE TITLE
Low fsk rssi 1.6.0/3.0.1

### ISSUE THREAD

**Issue by Joshadam0057** [FrSkyRC/RF_Feedback_Group#77]
Was getting very low rssi(fsk) after updates, LoRa seemed strong

**Comment by Joshadam0057** [comment]
Tw-gr6

**Comment by EngelMT** [comment]
@Joshadam0057 Bertrand trnsfered your issue to the RF Github Group because it is an RF issue,

**Comment by Joshadam0057** [comment]
Ahh, ok..thankyou.  Merry Christmas
