### ISSUE TITLE
Rx voltage

### ISSUE THREAD

**Issue by lotus1235** [FrSkyRC/RF_Feedback_Group#80]
Hello, I fly sailplanes and am wiring the wing servos. Flaps and ailerons in each wing. To reduce the number of wires, available space is limited, can I us the (+) and (-) to supply power to the the other servo, reduces the number of wires. I am concerned that I might not have enough voltage for both servos coming off the common 2 leads. Running xact 5700 with 8 volts to the gr8 rx.
Thanks

**Comment by SmartTommy** [comment]
could you tell me how many servos you connect to your gr8 RX?  could you show us the diagrammatic sketch?

**Comment by lotus1235** [comment]
6 servos, xact 5600, 8.0 volts from 3s lipoSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: LiNan ***@***.***> Date: 12/23/24  9:20 PM  (GMT-05:00) To: FrSkyRC/RF_Feedback_Group ***@***.***> Cc: lotus1235 ***@***.***>, Author ***@***.***> Subject: Re: [FrSkyRC/RF_Feedback_Group] Rx voltage (Issue #80) 
could you tell me how many servos you connect to your gr8 RX?  could you show us the diagrammatic sketch?

**Comment by SmartTommy** [comment]
> 6 servos, xact 5600, 8.0 volts from 3s lipo

did you mean you use 3S lipo---->BEC--->8.0V----> 6 5600(5700?) Servos and Rx?

what is your BEC type? is it stronger enough to power your servos?

**Comment by lotus1235** [comment]
No bec, esc 60 ampSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: LiNan ***@***.***> Date: 12/23/24  9:54 PM  (GMT-05:00) To: FrSkyRC/RF_Feedback_Group ***@***.***> Cc: lotus1235 ***@***.***>, Author ***@***.***> Subject: Re: [FrSkyRC/RF_Feedback_Group] Rx voltage (Issue #80) 

6 servos, xact 5600, 8.0 volts from 3s lipo

did you mean you use 3S lipo---->BEC--->8.0V----> 6 5600(5700?) Servos and Rx?
what is your BEC type? is it stronger enough to power your servos?

**Comment by SmartTommy** [comment]
please make sure your power for the Rx and the Servos > 0.3A + 1.2A(Stall Current)* number Of servos

**Comment by lotus1235** [comment]
Thank you Tommy.

**Comment by lotus1235** [comment]
8 amp bec, 20 amp max for .5 seconds
