### ISSUE TITLE
New Lua Script and SR6 mini

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/RF_Feedback_Group#81]
Hello,
I just updated the SR6 mini with the V3 and tried to calibrate after the update.

It make me crazy to calibrate because the RX PNG during the calibration process don't show the design of the SR6 mini.

Could be a good idea to update the LUA with the PNG if SR6 is detected !

Thank you

**Comment by Nicholas-Luoyi** [comment]
We will add it

**Comment by Nicholas-Luoyi** [comment]
Please update the script to 3.0.2 and check it

**Comment by aviat40** [comment]
Updated, works fine. 
Good job.
Thanks
