### ISSUE TITLE
Can not adjust gyro gain on RB30

### ISSUE THREAD

**Issue by sigurdma** [FrSkyRC/RF_Feedback_Group#84]
I have X20pro on Ethos 1.6.0 and was using a RB30.
I test the RB30 (gyro) with a RX8Rpro.
I go to Device in X20 an use RB30 / RB40.
It only shows config menu (and failsafe/mapping).
I can connect and set gyro on/off.
But I dont see where I can adjust gain an so on.

**Comment by SmartTommy** [comment]
Hi， you can turn on/off the stable function in the "basic config"menu, and return to the "Receiver--->SxR--->Configure"

then you can adjust the parameter

**Comment by sigurdma** [comment]
Yes that works, tanks. Not so easy to guess, it should be a shortcut in the RB30 meny also.
